export const metadata = {
    title: "Auth Login",
    description: "Generated by Next.js",
};
export default function SignIn() {
    return (
        <>
            <h1>Page Signin</h1>
        </>
    )
}