export const metadata = {
  title: "Mypage Index",
  description: "Generated by create next app",
};
import MypageUser from "../../components/site/Mypage/MypageUser";
export default function About() {
  return (
    <>
      <h2>My Page Page</h2>
      <MypageUser />
    </>
  );
}
