export const metadata = {
  title: "Admin - Configs",
  description: "Generated by Next.js",
};
export default async function AdminConfigs() {
  return (
    <>
      <h2>Admin Configs Page</h2>
    </>
  );
}
