export const metadata = {
  title: "Login Admin",
  description: "Generated by Next.js",
};
import AdminFormLogin from "../../components/admin/AdminFormLogin";
export default function AdminLogin() {
  return (
    <>
      <AdminFormLogin />
    </>
  );
}
